Rails.application.routes.draw do
  resources :work_flow_transition_conditions
  resources :work_flow_process_tmps
  resources :work_flow_activity_definitions
  resources :user_upload_logs
  resources :user_info_to_branches
  resources :user_comments
  resources :us_states
  resources :title3s
  resources :title2s
  resources :title1s
  resources :titles
  resources :tff_to_tffgroups
  resources :template_form_fields
  resources :saved_publications
  resources :roletitles
  resources :registered_component_htmls
  resources :registered_components
  resources :publication_types
  resources :portrait_images
  resources :page_to_headline_assignments
  resources :page_contents
  resources :pages
  resources :order_status_trackers
  resources :migrations_locks
  resources :migrations
  resources :mediatypes
  resources :logins
  resources :lab_user_infos
  resources :lab_regions
  resources :lab_headlines
  resources :lab_complexes
  resources :lab_branches
  resources :lab_areas
  resources :lab_ad_sizes
  resources :join_user_to_assistants
  resources :imported_ma_news
  resources :imported_fa_news
  resources :import_new_branches
  resources :import_managers
  resources :import_ma_news
  resources :import_financial_advisors
  resources :import_fa_news
  resources :headlinecolortypes
  resources :headline_to_ad_size_assignments
  resources :function_to_group_assignments
  resources :form_field_values
  resources :form_field_types
  resources :featured_links
  resources :featured_headlines
  resources :export_users
  resources :excel_valid_params
  resources :eo_pk_tables
  resources :domains
  resources :diagnostics
  resources :designationformfieldvalues
  resources :designations
  resources :data_ref_types
  resources :data_ref2s
  resources :data_refs
  resources :customvalues
  resources :copied_categories
  resources :comment_to_orders
  resources :comments
  resources :clients
  resources :cdg_user_to_role_assignments
  resources :cdg_users
  resources :cdg_template_stage_data
  resources :cdg_templates
  resources :cdg_roles
  resources :cdg_permission_types
  resources :cdg_permissions
  resources :cdg_order_statuses
  resources :cdg_orders
  resources :cdg_nav_menu_items
  resources :cdg_function_groups
  resources :cdg_functions
  resources :cdg_faqs
  resources :cdg_configurations
  resources :category_to_categories
  resources :approval_details
  resources :additional_run_dates
  resources :ad_matrix_category_headlines
  resources :ad_matrix_categories
  resources :ad_library_nodes
  resources :activity_participant_assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'arfs/:id', action: :arf, controller: 'cdg_orders'
  get 'ingest_reports', action: :ingest_worm_reports, controller: 'cdg_orders'
  get 'generate_report', action: :csv_reports, controller: 'cdg_orders', defaults: { format: 'csv' }
  get 'create_package', action: :gather_and_compress_order, controller: 'cdg_orders'
  get '/', to: redirect('/cdg_orders')
end
